// Generated by build.rs from IANA XML
use once_cell::sync::Lazy;
use std::collections::HashMap;

pub static MT_TO_CF: Lazy<HashMap<&'static str, u16>> = Lazy::new(|| {
    let mut m = HashMap::new();
    m.insert("text/plain; charset=utf-8", 0);
    m.insert(r#"application/cose; cose-type="cose-encrypt0""#, 16);
    m.insert(r#"application/cose; cose-type="cose-mac0""#, 17);
    m.insert(r#"application/cose; cose-type="cose-sign1""#, 18);
    m.insert("application/ace+cbor", 19);
    m.insert("image/gif", 21);
    m.insert("image/jpeg", 22);
    m.insert("image/png", 23);
    m.insert("application/link-format", 40);
    m.insert("application/xml", 41);
    m.insert("application/octet-stream", 42);
    m.insert("application/exi", 47);
    m.insert("application/json", 50);
    m.insert("application/json-patch+json", 51);
    m.insert("application/merge-patch+json", 52);
    m.insert("application/cbor", 60);
    m.insert("application/cwt", 61);
    m.insert("application/multipart-core", 62);
    m.insert("application/cbor-seq", 63);
    m.insert("application/edhoc+cbor-seq", 64);
    m.insert("application/cid-edhoc+cbor-seq", 65);
    m.insert(r#"application/cose; cose-type="cose-encrypt""#, 96);
    m.insert(r#"application/cose; cose-type="cose-mac""#, 97);
    m.insert(r#"application/cose; cose-type="cose-sign""#, 98);
    m.insert("application/cose-key", 101);
    m.insert("application/cose-key-set", 102);
    m.insert("application/senml+json", 110);
    m.insert("application/sensml+json", 111);
    m.insert("application/senml+cbor", 112);
    m.insert("application/sensml+cbor", 113);
    m.insert("application/senml-exi", 114);
    m.insert("application/sensml-exi", 115);
    m.insert("application/yang-data+cbor; id=sid", 140);
    m.insert("application/coap-group+json", 256);
    m.insert("application/concise-problem-details+cbor", 257);
    m.insert("application/swid+cbor", 258);
    m.insert("application/pkixcmp", 259);
    m.insert("application/yang-sid+json", 260);
    m.insert("application/ace-groupcomm+cbor", 261);
    m.insert("application/ace-trl+cbor", 262);
    m.insert("application/eat+cwt", 263);
    m.insert("application/eat+jwt", 264);
    m.insert("application/eat-bun+cbor", 265);
    m.insert("application/eat-bun+json", 266);
    m.insert("application/eat-ucs+cbor", 267);
    m.insert("application/eat-ucs+json", 268);
    m.insert("application/coap-eap", 269);
    m.insert("application/dots+cbor", 271);
    m.insert("application/missing-blocks+cbor-seq", 272);
    m.insert(
        "application/pkcs7-mime; smime-type=server-generated-key",
        280,
    );
    m.insert("application/pkcs7-mime; smime-type=certs-only", 281);
    m.insert("application/pkcs8", 284);
    m.insert("application/csrattrs", 285);
    m.insert("application/pkcs10", 286);
    m.insert("application/pkix-cert", 287);
    m.insert("application/aif+cbor", 290);
    m.insert("application/aif+json", 291);
    m.insert("application/senml+xml", 310);
    m.insert("application/sensml+xml", 311);
    m.insert("application/senml-etch+json", 320);
    m.insert("application/senml-etch+cbor", 322);
    m.insert("application/yang-data+cbor", 340);
    m.insert("application/yang-data+cbor; id=name", 341);
    m.insert("application/td+json", 432);
    m.insert("application/tm+json", 433);
    m.insert("application/sdf+json", 434);
    m.insert("application/uccs+cbor", 601);
    m.insert("application/voucher+cose (TEMPORARY - registered 2022-04-12, extension registered 2025-03-07, expires 2026-04-12)", 836);
    m.insert("application/vnd.ocf+cbor", 10000);
    m.insert("application/oscore", 10001);
    m.insert("application/javascript", 10002);
    m.insert(
        r#"application/eat+cwt; eat_profile="tag:psacertified.org,2023:psa#tfm""#,
        10003,
    );
    m.insert(
        r#"application/eat+cwt; eat_profile="tag:psacertified.org,2019:psa#legacy""#,
        10004,
    );
    m.insert(
        "application/eat+cwt; eat_profile=2.16.840.1.113741.1.16.1",
        10005,
    );
    m.insert("application/vnd.oms.cellular-cose-content+cbor", 10006);
    m.insert("application/toc+cbor", 10570);
    m.insert("application/ce+cbor", 10571);
    m.insert(
        "application/toc+cbor;profile=2.16.840.1.113741.1.16.1",
        10572,
    );
    m.insert(
        "application/ce+cbor;profile=2.16.840.1.113741.1.16.1",
        10573,
    );
    m.insert("application/json", 11050);
    m.insert("application/cbor", 11060);
    m.insert("application/vnd.oma.lwm2m+tlv", 11542);
    m.insert("application/vnd.oma.lwm2m+json", 11543);
    m.insert("application/vnd.oma.lwm2m+cbor", 11544);
    m.insert("text/plain;charset=utf-8", 12000);
    m.insert("application/xml", 12041);
    m.insert("application/json", 12050);
    m.insert("text/css", 20000);
    m.insert("image/svg+xml", 30000);
    m
});

pub static CF_TO_MT: Lazy<HashMap<u16, &'static str>> = Lazy::new(|| {
    let mut m = HashMap::new();
    m.insert(0, "text/plain; charset=utf-8");
    m.insert(16, r#"application/cose; cose-type="cose-encrypt0""#);
    m.insert(17, r#"application/cose; cose-type="cose-mac0""#);
    m.insert(18, r#"application/cose; cose-type="cose-sign1""#);
    m.insert(19, "application/ace+cbor");
    m.insert(21, "image/gif");
    m.insert(22, "image/jpeg");
    m.insert(23, "image/png");
    m.insert(40, "application/link-format");
    m.insert(41, "application/xml");
    m.insert(42, "application/octet-stream");
    m.insert(47, "application/exi");
    m.insert(50, "application/json");
    m.insert(51, "application/json-patch+json");
    m.insert(52, "application/merge-patch+json");
    m.insert(60, "application/cbor");
    m.insert(61, "application/cwt");
    m.insert(62, "application/multipart-core");
    m.insert(63, "application/cbor-seq");
    m.insert(64, "application/edhoc+cbor-seq");
    m.insert(65, "application/cid-edhoc+cbor-seq");
    m.insert(96, r#"application/cose; cose-type="cose-encrypt""#);
    m.insert(97, r#"application/cose; cose-type="cose-mac""#);
    m.insert(98, r#"application/cose; cose-type="cose-sign""#);
    m.insert(101, "application/cose-key");
    m.insert(102, "application/cose-key-set");
    m.insert(110, "application/senml+json");
    m.insert(111, "application/sensml+json");
    m.insert(112, "application/senml+cbor");
    m.insert(113, "application/sensml+cbor");
    m.insert(114, "application/senml-exi");
    m.insert(115, "application/sensml-exi");
    m.insert(140, "application/yang-data+cbor; id=sid");
    m.insert(256, "application/coap-group+json");
    m.insert(257, "application/concise-problem-details+cbor");
    m.insert(258, "application/swid+cbor");
    m.insert(259, "application/pkixcmp");
    m.insert(260, "application/yang-sid+json");
    m.insert(261, "application/ace-groupcomm+cbor");
    m.insert(262, "application/ace-trl+cbor");
    m.insert(263, "application/eat+cwt");
    m.insert(264, "application/eat+jwt");
    m.insert(265, "application/eat-bun+cbor");
    m.insert(266, "application/eat-bun+json");
    m.insert(267, "application/eat-ucs+cbor");
    m.insert(268, "application/eat-ucs+json");
    m.insert(269, "application/coap-eap");
    m.insert(271, "application/dots+cbor");
    m.insert(272, "application/missing-blocks+cbor-seq");
    m.insert(
        280,
        "application/pkcs7-mime; smime-type=server-generated-key",
    );
    m.insert(281, "application/pkcs7-mime; smime-type=certs-only");
    m.insert(284, "application/pkcs8");
    m.insert(285, "application/csrattrs");
    m.insert(286, "application/pkcs10");
    m.insert(287, "application/pkix-cert");
    m.insert(290, "application/aif+cbor");
    m.insert(291, "application/aif+json");
    m.insert(310, "application/senml+xml");
    m.insert(311, "application/sensml+xml");
    m.insert(320, "application/senml-etch+json");
    m.insert(322, "application/senml-etch+cbor");
    m.insert(340, "application/yang-data+cbor");
    m.insert(341, "application/yang-data+cbor; id=name");
    m.insert(432, "application/td+json");
    m.insert(433, "application/tm+json");
    m.insert(434, "application/sdf+json");
    m.insert(601, "application/uccs+cbor");
    m.insert(836, "application/voucher+cose (TEMPORARY - registered 2022-04-12, extension registered 2025-03-07, expires 2026-04-12)");
    m.insert(10000, "application/vnd.ocf+cbor");
    m.insert(10001, "application/oscore");
    m.insert(10002, "application/javascript");
    m.insert(
        10003,
        r#"application/eat+cwt; eat_profile="tag:psacertified.org,2023:psa#tfm""#,
    );
    m.insert(
        10004,
        r#"application/eat+cwt; eat_profile="tag:psacertified.org,2019:psa#legacy""#,
    );
    m.insert(
        10005,
        "application/eat+cwt; eat_profile=2.16.840.1.113741.1.16.1",
    );
    m.insert(10006, "application/vnd.oms.cellular-cose-content+cbor");
    m.insert(10570, "application/toc+cbor");
    m.insert(10571, "application/ce+cbor");
    m.insert(
        10572,
        "application/toc+cbor;profile=2.16.840.1.113741.1.16.1",
    );
    m.insert(
        10573,
        "application/ce+cbor;profile=2.16.840.1.113741.1.16.1",
    );
    m.insert(11050, "application/json");
    m.insert(11060, "application/cbor");
    m.insert(11542, "application/vnd.oma.lwm2m+tlv");
    m.insert(11543, "application/vnd.oma.lwm2m+json");
    m.insert(11544, "application/vnd.oma.lwm2m+cbor");
    m.insert(12000, "text/plain;charset=utf-8");
    m.insert(12041, "application/xml");
    m.insert(12050, "application/json");
    m.insert(20000, "text/css");
    m.insert(30000, "image/svg+xml");
    m
});
